# Generated by Django 5.0.6 on 2024-05-14 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_id', models.CharField(max_length=100, unique=True)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('apply_status', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('kill_record', models.JSONField()),
                ('apply_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('item_price', models.FloatField()),
                ('item_description', models.TextField()),
                ('item_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=10)),
                ('lp_cost', models.FloatField()),
                ('item_quantity', models.PositiveIntegerField()),
                ('nickname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titan_main.item')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('pap', models.FloatField(default=0.0)),
                ('isk', models.FloatField(default=0.0)),
                ('skill', models.FloatField(default=0.0)),
                ('lp', models.FloatField(default=0.0)),
                ('used_lp', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
