# Generated by Django 5.0.6 on 2024-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titan_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='character_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
